-- CreateEnum
CREATE TYPE "WebsiteCategory" AS ENUM ('DEVELOPMENT', 'STREAMING', 'DOCUMENTATION', 'GAMING', 'SOCIAL_MEDIA', 'E_COMMERCE', 'EDUCATION', 'NEWS', 'FINANCE', 'HEALTH', 'PRODUCTIVITY', 'DESIGN', 'MUSIC', 'VIDEO', 'CLOUD_STORAGE', 'EMAIL', 'FORUM', 'BLOG', 'TRAVEL', 'FOOD', 'SPORTS', 'TECHNOLOGY', 'ENTERTAINMENT', 'BUSINESS', 'MARKETING', 'SCIENCE', 'GOVERNMENT', 'NONPROFIT', 'PERSONAL', 'OTHER');

-- AlterTable
ALTER TABLE "Navly" ADD COLUMN     "category" "WebsiteCategory" NOT NULL DEFAULT 'OTHER';
